[tool.poetry]
name = "ccy"
version = "1.4.0"
description = "Python currencies"
authors = ["Luca Sbardella <luca@quantmind.com>"]
license = "BSD"
readme = "README.rst"
packages = [
    { include = "ccy" }
]

[tool.poetry.dependencies]
python = "^3.8,<3.13"
python-dateutil = "^2.8.2"
pycountry = "^22.3.5"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.10.1"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
mypy = "^1.4.0"
ruff = "^0.0.277"
types-python-dateutil = "^2.8.19.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
disallow_untyped_calls = false
disallow_untyped_defs = false
warn_no_return = false

[[tool.mypy.overrides]]
module = "pycountry.*"
ignore_missing_imports = true
