[tool.poetry]
name = "ccy"
version = "1.4.0"
description = "Python currencies"
authors = ["Luca Sbardella <luca@quantmind.com>"]
license = "BSD"
readme = "readme.md"
packages = [
    { include = "ccy" }
]

[tool.poetry.dependencies]
python = "^3.10,<3.13"
python-dateutil = "^2.8.2"
pycountry = "^22.3.5"

[tool.poetry.group.dev.dependencies]
black = "^23.9.0"
isort = "^5.10.1"
pytest-cov = "^4.0.0"
mypy = "^1.5.1"
ruff = "^0.0.291"
types-python-dateutil = "^2.8.19.13"

[tool.poetry.group.book]
optional = true

[tool.poetry.group.book.dependencies]
jupyter-book = "^0.15.1"
jupyterlab = "^4.0.3"
jupytext = "^1.14.7"
ghp-import = "^2.1.0"
pandas = "^2.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.jupytext]
formats = "ipynb,myst"

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_no_return = true

[[tool.mypy.overrides]]
module = "pycountry.*"
ignore_missing_imports = true


[[tool.mypy.overrides]]
module = "ccy.tradingcentres.*"
ignore_errors = true
